### ISSUE TITLE
Simple exception testing using lambdas

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#1]
Add something like it was proposed in junit-team/junit#1055.

**Comment by marcphilipp** [comment]
junit-team/junit#1154 has another proposal.

**Comment by marcphilipp** [comment]
junit-team/junit#1154 has been merged into master in junit-team/junit@bdb1799a6b58c4ab40c418111333f4e8e1816e7e.

**Comment by sbrannen** [comment]
Closing this issue, since this functionality already exists in the prototype in the `Assertions` class.
