### ISSUE TITLE
Introduce method call level exception expected 

### ISSUE THREAD

**Issue by dinesh707** [junit-team/junit-lambda#22]
Currently if we need to test some method is throwing an exception by following methods

 @Test(expected=BalhException.class)

OR 

@Test
public void meTest() {
int a = 10;
int b = 20;
Cat c = new Cat();
try{
c.talk()
fail("this is bad")
} catch(BalhException e) {
//this is good
}
}

I prefer the 2nd option since there i can really tell that the point of failure is c.talk() method. 

So I suggest a annotation for a method execution level tests which would look like following

@Test
public void meTest() {
int a = 10;
int b = 20;
Cat c = new Cat();
@MethodTest(expected=BalhException.class)
c.talk()

}

**Comment by schauder** [comment]
I think the Assertion mechanism for exception which is currently proposed is nicer than all three variants: https://github.com/junit-team/junit-lambda/wiki/Prototype-Writing-Test-Cases#assertions

**Comment by dinesh707** [comment]
@schauder I'll read more on already proposed docs. I Agree with you and the suggestion in the link is quite clean.

**Comment by marcphilipp** [comment]
@schauder @dinesh707 Thanks!
