### ISSUE TITLE
Prepare repository for alpha phase

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#24]
1. [x] Tag current master with `prototype-1`.
1. [x] Change group id to `org.junit`.
1. [x] Delombok everything.
1. [x] Delete elements we want to rewrite (e.g. primarily the implementation of `junit5-engine`) using `JUnit Team <team@junit.org>` as the Git author
1. [x] Remove all author tags
1. [x] Create test module and move existing tests for published modules there.
1. [x] Remove dependencies on `junit:junit:4.12` from all existing modules except junit4-engine, junit4-launcher-runner, and open-test-alliance.

_JUnit Team_ user configuration for `~/.gitconfig`:

```
[user]
	name = JUnit Team
	email = team@junit.org
```

**Comment by mmerdes** [comment]
we realized our understanding of yesterday's discusstion.
please do check if everything is fine.

**Comment by mmerdes** [comment]
excellent bdfl-work - too fast for us :)

**Comment by bechte** [comment]
:+1: Well done. Thanks.
