### ISSUE TITLE
Experiment with alternative approach for Callbacks for @Before/@After

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#28]
Alternative solution for `pre`/`post` callbacks.

**Comment by jlink** [comment]
Added branch https://github.com/junit-team/junit-lambda/tree/issue28-extension-alternative with alternative proposal for extension model

**Comment by jlink** [comment]
Merged into https://github.com/junit-team/junit-lambda/tree/issue28-extension-points master.
