### ISSUE TITLE
Move Open Test Alliance to new project

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#30]
- [X] separate GitHub organization
- [X] register domain name
- [X] create repo
- [X] copy code into new repo
- [x] publish artifacts in Sonatype's snapshot repo (@marcphilipp)
- [x] use it in junit modules
- [x] remove `open-test-alliance` module from JUnit Lambda repository
- [x] invite people from #12
- [x] incorporate feedback from #12

**Comment by sbrannen** [comment]
New GitHub organization:

https://github.com/ota4j-team

**Comment by sbrannen** [comment]
New repository:

https://github.com/ota4j-team/opentest4j

**Comment by marcphilipp** [comment]
I've opened an issue on Sonatype's JIRA to grant us access to push to Maven Central with the new group id:
https://issues.sonatype.org/browse/OSSRH-19371

**Comment by sbrannen** [comment]
Thanks, @marcphilipp!

I'm watching that Sonatype JIRA issue now.

**Comment by marcphilipp** [comment]
Snapshots are now uploaded to Sonatype's snapshot repo by Jenkins.

**Comment by sbrannen** [comment]
`org.opentest4j` snapshots are now consumed by JUnit Lambda.

**Comment by sbrannen** [comment]
Officially moving all discussions to https://github.com/ota4j-team/opentest4j now.
