### ISSUE TITLE
Should JUnit support mocking as a basic feature

### ISSUE THREAD

**Issue by dinesh707** [junit-team/junit-lambda#32]
There are some object mocking frameworks available such as Mockito. Should JUnit care and give functionality to junit users to mock variables?

If it is yes, then I would like to see some form of automatic mocking mechanism for JPA meta-model like classes. But again the mocking should should be scoped for a single test. If im explaining the problem further, now when the hibernate meta models are generated they define variables as "SingularAttribute<?,?> blah". So each of those fields will be null on Junit testing level. So the verification will not work properly unless you first mock a value and set them.

**Comment by kcooney** [comment]
I don't think JUnit should complete with the existing mocking libraries. I do think we should provide extension points that make it easy to integrate with a mocking librariy, but IMHO it should be obvious what is going on.

I do this when I use Mockito:

    public class MyTest {
      @Mock private FooDao mockDao;
      public final TestRule injectMocks = new InjectMocks(this);
      private Sut sut;

      @Before
      public void createSubjectUnderTeat() {
        // cannot assign "sut" at declaration time because
        // the mock fields haven't been initialized
        sut = new Sut(mockDao);
      }

The question is do we try to reduce the amount of code required, and if so, how much can we reduce it before it's not obvious what is going on.

**Comment by dinesh707** [comment]
I use '@InjectMocks' than setting them in the constructor which we don't have. But again InjectMocks will only inject fields which are annotated with '@Inject' in original class. Then in that case I need to set private methods by force using reflection which is not nice in how it looks at the end

**Comment by kcooney** [comment]
That is a reasonable example of reducing the amount of code in exchange for it being slightly less obvious what is going on. We should make it easy for projects like Mockito to provide these solutions.

II don't see how JUnit can make this easier for teams that don't use constructor injection, but perhaps Mockito can.

**Comment by sbrannen** [comment]
@kcooney, I can't resist asking... what exactly is a "subject under teat"? :wink:

**Comment by sbrannen** [comment]
Hi @dinesh707,

The JUnit team does not intend to provide any explicit support for mocking in the foreseeable future. Instead, users are free to use any mocking framework of their choice.

However, in the JUnit 5 prototype we already provide two extension points that mocking frameworks can choose to implement:

- [`InstancePostProcessor`](https://github.com/junit-team/junit-lambda/blob/master/junit5-api/src/main/java/org/junit/gen5/api/extension/InstancePostProcessor.java)
- [`MethodParameterResolver`](https://github.com/junit-team/junit-lambda/blob/master/junit5-api/src/main/java/org/junit/gen5/api/extension/MethodParameterResolver.java)

In fact, we also implemented a sample [`MockitoExtension`](https://github.com/junit-team/junit-lambda/blob/master/sample-extension/src/main/java/com/example/mockito/MockitoExtension.java) that implements both of these extension points. If you take a look at [MockitoExtensionInBaseClassTest](https://github.com/junit-team/junit-lambda/blob/master/sample-extension/src/test/java/com/example/mockito/MockitoExtensionInBaseClassTest.java) you can see both extension points in action (i.e., field injection via `@Mock` and method injection via `@InjectMock`).

With that in mind, I will go ahead and close this issue.

Regards,

Sam
