### ISSUE TITLE
Redefine and implement TestExecutionListener

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#34]
- [X] Change interface, implementors, and callers.
- [x] Document semantics in Javadoc.

**Comment by mmerdes** [comment]
probably missing events:
* TestExecutionListener.containerStarted(), TestExecutionListener.containerEnded()

**Comment by mmerdes** [comment]
testStarted(): should this be fired before or after invocation of @Before-methods (and extensions)?

**Comment by sbrannen** [comment]
> TestExecutionListener.testStarted(): should this be fired before or after invocation of @Before-methods (and extensions)?

`testStarted()` should be fired _before_ `@BeforeEach` methods but _only if_ the test is not _skipped_.

**Comment by sbrannen** [comment]
When you say "_container_" for `containterStarted()`, are you generically referring to things like packages and test classes (i.e., nodes in the execution tree that are not themselves _tests_)?

**Comment by mmerdes** [comment]
yes, that was the intention

**Comment by sbrannen** [comment]
Then, yes, we should consider adding events for container-level execution.

We already have _callbacks_ at the class level for both the programming model and the extension model. Thus adding _events_ for those would seem to be logical.

**Comment by jlink** [comment]
The container event must be a bit more sophisticated than just started() and ended() since there's the possibility of failures (e.g. through exceptions in beforeAll) and success with exceptions in afterAll().

**Comment by sbrannen** [comment]
I agree with @jlink: container events should provide context.

**Comment by sbrannen** [comment]
Furthermore, a container can also be _skipped_ due to conditional test execution just like an individual test. So we should probably added `containerSkipped()`.

**Comment by marcphilipp** [comment]
Since `TestDescriptor` has `isTest()` it could also have `isContainer()` and we could just use the existing events. Opinions?

**Comment by sbrannen** [comment]
Summarizing the aforementioned events for containers:

- `containerStarted(TestDescriptor)`
- `containerSkipped(TestDescriptor, Throwable)`
- `containerAborted(TestDescriptor, Throwable)`: not sure we actually need this, but I'll leave it open to discussion.
- `containerFailed(TestDescriptor, Throwable)`
- `containerSucceeded(TestDescriptor)`

**Comment by sbrannen** [comment]
@marcphilipp, introducing `isContainer()` is indeed perhaps the more elegant solution... as opposed to duplicating all events (as in my previous comment).

**Comment by sbrannen** [comment]
Analogous to my previous comment regarding tests, the following holds for the semantics of containers:

`containerStarted()` should be fired _before_ `@BeforeAll` methods but _only if_ the container is not _skipped_.

**Comment by sbrannen** [comment]
If we decide to introduce `isContainer()` in `TestDescriptor` and forego duplication of event callbacks in the listener, we should then rethink the **test** prefix of all of the existing methods in `TestExecutionListener` since `testStarted()` is misleading for a _container_.

We could of course document that _test_ in this context can refer to either an actual test or a container, but doing so would likely still lead to confusion.

**Comment by marcphilipp** [comment]
I think we could call it `executionStarted` and so on.

**Comment by sbrannen** [comment]
:+1: 

Revised API to handle both tests and containers:

- `executionStarted(TestDescriptor)`
- `executionSkipped(TestDescriptor, Throwable)`
- `executionAborted(TestDescriptor, Throwable)`
- `executionFailed(TestDescriptor, Throwable)`
- `executionSucceeded(TestDescriptor)`

**Comment by sbrannen** [comment]
We should also rename `dynamicTestFound()` to `dynamicTestRegistered()`.

"Found" implies that a dynamic test was found during the _discovery_ phase, when in fact, a dynamic test will be _registered_ programmatically at some point after the _execution_ phase has begun.

**Comment by jlink** [comment]
`Skipped` could also be a property of `TestDescriptor` so that the exception wouldn't be necessary any more.

**Comment by marcphilipp** [comment]
#### Alternative Proposal

- `executionStarted(TestDescriptor)`
- `executionFinished(TestDescriptor, TestResult)`

where 

```java
public class TestResult {

	public enum Status {
		SUCCESSFUL, SKIPPED, ABORTED, FAILED
	}

	private final Status status;
	private final String message;
	private final Throwable exception;

	public static TestResult successful() {
		return new TestResult(SUCCESSFUL, null, null);
	}

	public static TestResult skipped(String message) {
		return new TestResult(SKIPPED, message, null);
	}

	public static TestResult aborted(Throwable exception) {
		return new TestResult(ABORTED, null, exception);
	}

	public static TestResult failed(Throwable exception) {
		return new TestResult(FAILED, null, exception);
	}

	public TestResult(Status status, String message, Throwable exception) {
		Preconditions.notNull(status, "status must not be null");
		this.status = status;
		this.message = message;
		this.exception = exception;
	}

	public Status getStatus() {
		return status;
	}

	public Optional<String> getMessage() {
		return Optional.ofNullable(message);
	}

	public Optional<Throwable> getException() {
		return Optional.ofNullable(exception);
	}

}
```

**Comment by marcphilipp** [comment]
### New proposal of whole team

- `executionSkipped(TestDescriptor, String reason)`
- `executionStarted(TestDescriptor)`
- `executionFinished(TestDescriptor, TestResult)`

where 

```java
public class TestResult {

	public enum Status {
		SUCCESSFUL, ABORTED, FAILED
	}

	private final Status status;
	private final String message;
	private final Throwable exception;

	public static TestResult successful() {
		return new TestResult(SUCCESSFUL, null, null);
	}

	public static TestResult aborted(Throwable exception) {
		return new TestResult(ABORTED, null, exception);
	}

	public static TestResult failed(Throwable exception) {
		return new TestResult(FAILED, null, exception);
	}

	public TestResult(Status status, String message, Throwable exception) {
		Preconditions.notNull(status, "status must not be null");
		this.status = status;
		this.message = message;
		this.exception = exception;
	}

	public Status getStatus() {
		return status;
	}

	public Optional<String> getMessage() {
		return Optional.ofNullable(message);
	}

	public Optional<Throwable> getException() {
		return Optional.ofNullable(exception);
	}

}
```

**Comment by marcphilipp** [comment]
```java
public interface TestExecutionListener {

	default void testPlanExecutionStarted(TestPlan testPlan) {
	}

	default void testPlanExecutionFinished(TestPlan testPlan) {
	}

	default void dynamicTestRegistered(TestIdentifier testIdentifier) {
	}

	default void executionStarted(TestIdentifier testIdentifier) {
	}

	default void executionSkipped(TestIdentifier testIdentifier, String reason) {
	}

	default void executionFinished(TestIdentifier testIdentifier, TestExecutionResult result) {
	}
}
```

**Comment by marcphilipp** [comment]
Done.
