### ISSUE TITLE
Introduce simple ToStringBuilder

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit-lambda#47]
In order to avoid code duplication and dependencies on third-party libraries such as Apache Commons, introduce a simple `ToStringBuilder` that generates output similar to that which is currently generated by `ConditionEvaluationResult#toString()`.

**Comment by sbrannen** [comment]
@marcphilipp,

I just pushed a basic implementation for a `ToStringBuilder` (along with `ToStringBuilderTests`) to a [feature branch](https://github.com/sbrannen/junit-lambda/tree/issue47-to-string-builder).

Does the `ToStringBuilder` in the above branch meet your current needs, or did you have something more robust in mind?

**Comment by marcphilipp** [comment]
@sbrannen Thanks, that's about what I had in mind. :+1: 

We should merge this as soon as Stefan's branch has been merged.

**Comment by sbrannen** [comment]
Sure. Thanks for the feedback.

I'll add support for primitive arrays before merging into `master`.

**Comment by marcphilipp** [comment]
:+1:

**Comment by sbrannen** [comment]
Here's the support for arrays of primitives...

https://github.com/sbrannen/junit-lambda/commit/d324b7d902a065c4e31d71c111662a683108b809

**Comment by marcphilipp** [comment]
I've come up with an alternative implementation for supporting primitive arrays here:
sbrannen/junit-lambda#1

**Comment by sbrannen** [comment]
Thanks, @marcphilipp.

Your PR looks good.... but I'm not so sure that I can agree that `23` is more _magical_ than `99`. :wink: 

I'll go ahead and merge your changes.

**Comment by marcphilipp** [comment]
That happened by accident with some intermediate steps. 😊

**Comment by bechte** [comment]
@Sam: 23 is prime. ;-)

(just kidding)

**Comment by marcphilipp** [comment]
@sbrannen From my point of view, we can go ahead and merge your branch into master. Do you have time to do it or shall I take over?

**Comment by sbrannen** [comment]
I'll take care of it.

**Comment by sbrannen** [comment]
Merged into `master` in https://github.com/junit-team/junit-lambda/commit/3e6edc2dc68d95052afc1302df93be3f0958a35f.

**Comment by marcphilipp** [comment]
Thanks!
