### ISSUE TITLE
Tests for junit-console

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#49]
I started to make it testable in #37.

**Comment by marcphilipp** [comment]
@sbrannen Do you have time to take a look at https://github.com/junit-team/junit-lambda/blob/master/junit-console/src/main/java/org/junit/gen5/console/tasks/ExecuteTestsTask.java#L61-L69 ?

**Comment by sbrannen** [comment]
I'm taking a look now.

**Comment by sbrannen** [comment]
FYI: I'm about to push minor changes to `master`.

**Comment by sbrannen** [comment]
OK. I pushed two commits in conjunction with #50.

Let me know if you have any questions.

**Comment by marcphilipp** [comment]
Looks good to me, thanks!
