### ISSUE TITLE
Rename junit4-launcher-runner to junit4-runner

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#55]
For greater clarity:

- [x] Rename the `junit4-launcher-runner` module to `junit4-runner`.
- [x] Rename the `org.junit.gen5.junit4runner` package to `org.junit.gen5.junit4.runner`.
- [x] Update artifact ID in README, Wiki, etc.

**Comment by marcphilipp** [comment]
What should the package `org.junit.gen5.junit4runner` be called then?

**Comment by sbrannen** [comment]
How about `org.junit.gen5.junit4.runner`?

If we go that route, I'm very tempted to rename `org.junit.gen5.engine.junit4` to `org.junit.gen5.junit4.engine` for consistency.

I realize that would then be inconsistent with `org.junit.gen5.engine.junit5`, but I could live with that.

Thoughts?

**Comment by jlink** [comment]
Org.junit.gen5.junit5on4

It's a temporary thing anyway, so doesn't matter much IMO.

**Comment by jlink** [comment]
I'd prefer engine in front. The JUnit 5 on 4 runner will go away anyway.

**Comment by marcphilipp** [comment]
Team Decision: `org.junit.gen5.junit4.runner`

**Comment by sbrannen** [comment]
(y)

**Comment by sbrannen** [comment]
FYI: I split up the orginial TODO into 4 TODOs.

**Comment by sbrannen** [comment]
Resolving this issue.

See related commits for details.

**Comment by marcphilipp** [comment]
:+1:
