### ISSUE TITLE
Agree and document team conventions for automated tests

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#66]
### Test Class Naming

I think we need a naming convention for our test classes. At the moment we have test classes that end with `Test`, `Tests`, and `TestCase`. Personally, I would prefer one of the first two variants.

### Assertions

In addition, we should agree on how to write assertions. At the moment we have tests that use JUnit 4's `Assert`, some use our new `Assertions` class, others use AssertJ's `Assertions`. Since we plan to migrate our tests to use JUnit 5 at some point, I would propose that we do not use anything in JUnit 4, particularly not `org.junit.Assert`. Instead, I think, we should use our own `Assertions` were feasible and AssertJ, where we need its power.

### Test Doubles

We had a brief discussion on Skype regarding a mocking framework. I've added Mockito to the test classpath and used it in a couple of tests. Other tests use hand-written stubs or spys. I think we can go with Mockito where easier and write doubles ourselves when we think it clearer.

**Comment by marcphilipp** [comment]
@junit-team/junit-lambda What are your opinions on this?

**Comment by jlink** [comment]
*TestCase is for those examples that should not be picked up by the build.

2015-12-16 9:20 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by marcphilipp** [comment]
Not exclusively. Right now there is `AbstractJUnit5TestEngineTestCase`, for example, too.

**Comment by jlink** [comment]
Test Class Naming:
*Tests speaks more truth but I can live with either.
*TestCase for examples (that might fail)

Assertions:
Let's move to Assertions.* We should do that systematically, though.

Test Doubles:
Nowadays I hardly ever hand-code mocks as soon as I have decided to use a
mock framework at all. So, your suggestion is fine.

Johannes

2015-12-16 9:20 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by sbrannen** [comment]
I thought we had already agreed on several of these points. So I'll chime in here with what I believe we agreed upon (or what I think we should do).

## Test Class Naming

- `*Tests` for all test classes that run as part of the Gradle build (i.e., our test suite)
- `*TestCase` for all test classes that are themselves run or used by `*Tests` classes in our test suite

## Assertions

- Use JUnit 5 `Assertions` wherever possible.
  - The use of JUnit 4 `Assert` was only intended as an interim solution; any remaining use of JUnit 4 `Assert` should be migrated to JUnit 5 `Assertions`.
- Use AssertJ `Assertions` whenever we need richer assertions than those provided by JUnit 5 `Assertions`.

## Test Doubles

- Use Mockito whenever feasible.
- Implement custom test doubles when a Mockito mock does not suffice -- for example, the `TrackingEngineExecutionListener`.

**Comment by dsaff** [comment]
Just to be contrarian, I've found custom test doubles to be preferable to
mocking frameworks universally.

If y'all are 100% on-board with Mockito, I won't make a big fuss, but if
you're on the fence, happy to provide further rationales.

   David Saff

**Comment by bechte** [comment]
I like to use test doubles and prefer them over mocking frameworks, too. initially it might take some additional time to create them but if we put them in one location and commit ourselves on naming conventions we will soon have the most commonly used test doubles in place. I also like the flexibility custom test doubles give you especially when it comes to true mocking (having validation rules in on place).

I tend to only use mockito when I cannot use a test double, e.g. to mock final classes. in such cases the use of mocking frameworks is great. we probably won't have much of those though. ;-)

Anyways, I am fine with either way.

Stefan

**Comment by marcphilipp** [comment]
Thanks for chiming in, @dsaff!

I think we all have sufficient experience writing unit tests and using mocking frameworks. I don't want to get into the discussion at the moment. I think there are compelling reasons for both sides. I believe it comes down to a matter of personal preference in the end. In addition, I think we have more important things to discuss right now.

Therefore, I propose that we add the following to `CONTRIBUTING.MD`:

> ## Tests
> 
> ### Naming
> 
> - All test classes must end with a `Tests` suffix.
> - Examples of test classes that should not be picked up by the build must end with a `TestCase` suffix.
>
> ### Assertions
> 
> - Use `org.junit.gen5.api.Assertions` wherever possible.
> - Use AssertJ when richer assertions are needed.
> - Do not use `org.junit.Assert` or `junit.framework.Assert`.
>
> ### Mocking
>
> - Use either Mockito or hand-written test doubles.

If there are no objections, I will update `CONTRIBUTING.MD` in the next few days.

**Comment by kcooney** [comment]
I generally prefer Mockito for interaction-based testing, and for simple fakes. When using hand-crafted fakes, I generally write tests for the fake unless they are trivial.

To be contrian, I prefer `FooTest` over `FooTests`.

For abstract test classes, I tend to use `FooTestCase` but would be fine with `AbstractFooTest` (I never extend test classes from concrete classes)

**Comment by jlink** [comment]
No objections, Marc.

2015-12-16 21:46 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by mmerdes** [comment]
Marc,

Fine with me,
Thanks for bringing it up

Good Night
Matthias

Marc Philipp <notifications@github.com> schrieb am Mi., 16. Dez. 2015 um
21:46:

**Comment by sbrannen** [comment]
No objections, @marcphilipp. Just note the minor changes I made to your proposal (i.e., the edited comment).
