### ISSUE TITLE
Migrate tests in junit-tests to JUnit5

### ISSUE THREAD

**Issue by jlink** [junit-team/junit-lambda#72]
- [x] meta
- [x] launcher
- [x] engine-api 
- [x] commons
- [x] junit5 engine
- [x] console

**Comment by marcphilipp** [comment]
Code coverage should work since it doesn't know anything about how the code is executed.

**Comment by jlink** [comment]
Disable now works.

**Comment by marcphilipp** [comment]
I'll start migrating the console tests now.

**Comment by marcphilipp** [comment]
I've changed all the tests to be named `*Tests`, use JUnit 5 `Assertions`, and annotations.

However, since we run them using our custom Gradle plugin, coverage is indeed not reported correctly at the moment. I'll look into fixing it next.

**Comment by marcphilipp** [comment]
Code coverage is working again now:
https://codecov.io/github/junit-team/junit-lambda?ref=85cf5ca2e0431f4dae9880bcbc9d1c4509cecfd7
