### ISSUE TITLE
Ensure TestIdentifier is Serializable

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#79]
The only thing preventing this at the moment is `TestSource` and its subclasses, e.g. `Class<?>` is not `Serializable` but could be replaced by the fully-qualified class name as a `String`.

**Comment by bechte** [comment]
We could require all `TestSource`s to implement `Serializable`, such that they can decide how to serialize themselves. E.g. `JavaTestSource` might store the full qualified name of a class or method as proposed. Is that what you mean?

**Comment by marcphilipp** [comment]
Yep.

**Comment by kcooney** [comment]
`java.lang.Class` is serializable: https://docs.oracle.com/javase/7/docs/api/serialized-form.html#java.lang.Class

**Comment by marcphilipp** [comment]
@kcooney That's true. However, `java.lang.reflect.Method` is not.
