### ISSUE TITLE
 Introduce blacklist of errors that always terminate test plan execution

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit-lambda#83]
## Status Quo

Exception handling code within the `JUnit5TestEngine` currently treats all errors the same. For example, if an `OutOfMemoryError` is thrown it will be treated the same as an `AssertionError`: both will fail the test, but in the case of the former the current test plan should actually be halted.

## Deliverables
- [x] Introduce a _blacklist_ of errors that should always terminate test plan execution.
- [x] Refactor all exception handling code within the `JUnit5TestEngine` so that blacklisted errors always terminate the current `TestPlan` immediately.

**Comment by mmerdes** [comment]
Team decision: Implement for OutOfMemoryError.

**Comment by sbrannen** [comment]
Resolved in commit a02c0e24af370ced24d8fa9d758b1a1db396796f
