### ISSUE TITLE
Introduce disclaimer for junit-commons

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit-lambda#96]
In order to avoid any confusion about the intent of the `junit-commons` module, we need to provide a clear disclaimer to convey the fact that such utilities are intended for internal usage only.

**Comment by jlink** [comment]
Would'nt our yet to introduce API annotations cover that?

Von meinem iPad gesendet

**Comment by sbrannen** [comment]
Yes, #63 is certainly related to this, but providing actual documentation in the form of Javadoc within the `junit-commons` module is IMO a good idea anyway: it's much more difficult to ignore the **DISCLAIMER** than it is to miss the presence of a non-standard annotation.

Neither the disclaimer nor the presence of such an annotations is enforceable anyway. So the more we warn the user, the better. :wink:

**Comment by sbrannen** [comment]
Addressed in 807c918c5470b3bcad36576d9c8a28a42aa2b8ca.

**Comment by jlink** [comment]
My plan was to create the disclaimer automatically from the annotation.

Von meinem iPad gesendet

**Comment by sbrannen** [comment]
What do you mean by "create"?

Do you plan to insert text into the generated Javadoc?

**Comment by marcphilipp** [comment]
That would require a custom doclet, wouldn't it?

**Comment by jlink** [comment]
Exactly. In an annotation processor.

**Comment by jlink** [comment]
Or a doclet could pick it up.

**Comment by marcphilipp** [comment]
Would be great if we could make that possible! If we do, we can probably remove the manual disclaimers.

**Comment by sbrannen** [comment]
Keep in mind that developers who download source JARs and view Javadoc in their IDEs via those source JARs (as opposed to Javadoc JARs) will **not** see any generated disclaimer and will likely not pay heed to non-standard annotations.
